services:

  postgres:
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NatsumiChan
      POSTGRES_DB: dash
      POSTGRES_HOST: postgres:5432
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  dash:
    image: dash:latest
    build: .
    restart: "no"
    volumes:
      - ./local/directory/on/host:/app/files
    environment:
      FILE_STORAGE_PATH: /app/files/
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - postgres
volumes:
  postgres_data: